name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@81d310742121c928ea9c8bbd407b4217b432ae02  # v2.0.0

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Install required board core
        run: arduino-cli core install arduino:avr@1.8.7

      - name: Static analysis
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --language=c++ --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=checkersReport --error-exitcode=1 HeaterFlameDetection/*.ino HeaterFlameDetection/*.h

      - name: Compile Arduino project
        run: |
          arduino-cli compile --fqbn arduino:avr:nano ./HeaterFlameDetection
